CREATE SCHEMA IF NOT EXISTS customer_core;
CREATE SCHEMA IF NOT EXISTS customer_legacy;

CREATE TABLE customer_core.customer (
    id UUID PRIMARY KEY,
    email TEXT,
    name JSONB,
    status TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    phone TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_legacy.customer_identifier (
    legacy_customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier_kind VARCHAR(32) NOT NULL,
    identifier_value VARCHAR(255) NOT NULL,
    customer_reference VARCHAR(64),
    source_system VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (identifier_kind, identifier_value)
);

CREATE INDEX customer_legacy_customer_reference_idx
    ON customer_legacy.customer_identifier (customer_reference);
