import type {
  ApiEndpoint,
  CompatibilityCheck,
  DeploymentRecord,
  EnterpriseResource,
  IncidentRecord,
  LabService,
  MappingSuggestion,
  MemoryPattern,
  WorkspaceEnvironment,
} from "@/lib/types";

export const environments: WorkspaceEnvironment[] = ["Production", "Staging", "Development"];

export const discoveryTotals = [
  { label: "Compute resources", value: 27, provider: "AWS + Azure" },
  { label: "Databases", value: 11, provider: "Cloud + self-managed" },
  { label: "Services", value: 43, provider: "Kubernetes + VMs" },
  { label: "APIs", value: 18, provider: "REST + SOAP" },
  { label: "Queues", value: 7, provider: "Kafka + managed queues" },
  { label: "Identity providers", value: 4, provider: "Okta + directory" },
  { label: "SaaS integrations", value: 12, provider: "Salesforce + SaaS" },
] as const;

export const resources: EnterpriseResource[] = [
  {
    id: "acme",
    name: "ACME production estate",
    shortName: "ACME",
    provider: "Enterprise",
    kind: "Environment",
    environment: "Production",
    status: "warning",
    owner: "Platform operations",
    description: "Cross-cloud production boundary discovered from connected providers and runtime evidence.",
    dependencies: ["aws", "azure", "okta"],
    dependents: [],
    region: "Multi-region",
    permissions: ["environment:read"],
    tags: ["customer", "production"],
    x: 50,
    y: 7,
  },
  {
    id: "aws",
    name: "AWS production account",
    shortName: "AWS",
    provider: "AWS",
    kind: "Cloud account",
    environment: "Production",
    status: "healthy",
    owner: "Cloud platform",
    description: "Connected AWS account with EKS, EC2, RDS PostgreSQL, and S3 resources.",
    dependencies: [],
    dependents: ["acme", "eks", "customer-db"],
    region: "us-east-1",
    permissions: ["inventory:read", "network:read"],
    tags: ["cloud", "aws"],
    x: 27,
    y: 22,
  },
  {
    id: "azure",
    name: "Azure production subscription",
    shortName: "Azure",
    provider: "Azure",
    kind: "Cloud subscription",
    environment: "Production",
    status: "healthy",
    owner: "Cloud platform",
    description: "Connected Azure subscription with AKS and Azure SQL resources.",
    dependencies: [],
    dependents: ["acme", "aks"],
    region: "eastus",
    permissions: ["inventory:read", "network:read"],
    tags: ["cloud", "azure"],
    x: 73,
    y: 22,
  },
  {
    id: "okta",
    name: "ACME workforce identity",
    shortName: "Okta",
    provider: "Okta",
    kind: "Identity provider",
    environment: "Production",
    status: "healthy",
    owner: "Security engineering",
    description: "OIDC provider for workload and workforce authentication.",
    dependencies: [],
    dependents: ["acme", "customer-api"],
    region: "Global",
    permissions: ["client:read", "jwks:read"],
    tags: ["identity", "oidc"],
    x: 51,
    y: 40,
  },
  {
    id: "eks",
    name: "Customer workload cluster",
    shortName: "EKS",
    provider: "AWS",
    kind: "Kubernetes cluster",
    environment: "Production",
    status: "healthy",
    owner: "Platform operations",
    description: "Kubernetes 1.31 cluster hosting customer-facing and worker services.",
    dependencies: ["aws"],
    dependents: ["acme", "customer-api", "order-service"],
    region: "us-east-1",
    permissions: ["workload:read", "metrics:read"],
    tags: ["kubernetes", "compute"],
    x: 20,
    y: 43,
  },
  {
    id: "aks",
    name: "Enterprise integration cluster",
    shortName: "AKS",
    provider: "Azure",
    kind: "Kubernetes cluster",
    environment: "Production",
    status: "healthy",
    owner: "Integration platform",
    description: "Azure Kubernetes cluster hosting internal integration workloads.",
    dependencies: ["azure"],
    dependents: ["acme", "sync-worker"],
    region: "eastus",
    permissions: ["workload:read", "metrics:read"],
    tags: ["kubernetes", "integration"],
    x: 80,
    y: 43,
  },
  {
    id: "sync-worker",
    name: "Salesforce sync worker",
    shortName: "Sync worker",
    provider: "Azure",
    kind: "Worker service",
    environment: "Production",
    status: "warning",
    owner: "Revenue systems",
    description: "Consumes customer change events and synchronizes account state to Salesforce.",
    dependencies: ["aks", "salesforce"],
    dependents: [],
    region: "eastus",
    permissions: ["queue:consume", "salesforce:write"],
    tags: ["salesforce", "worker"],
    x: 82,
    y: 64,
  },
  {
    id: "customer-api",
    name: "Customer API",
    shortName: "Customer API",
    provider: "AWS",
    kind: "REST API",
    environment: "Production",
    status: "healthy",
    owner: "Customer domain",
    description: "Public customer lookup API with OIDC validation and PostgreSQL persistence.",
    dependencies: ["eks", "okta", "customer-db"],
    dependents: ["order-service"],
    region: "us-east-1",
    permissions: ["customer:read", "customer:write"],
    tags: ["api", "customer", "tier-1"],
    x: 18,
    y: 64,
  },
  {
    id: "order-service",
    name: "Order orchestration",
    shortName: "Orders",
    provider: "AWS",
    kind: "Worker service",
    environment: "Production",
    status: "healthy",
    owner: "Order domain",
    description: "Orchestrates order events and writes warehouse projections.",
    dependencies: ["eks", "customer-api", "kafka", "snowflake"],
    dependents: ["support-dashboard"],
    region: "us-east-1",
    permissions: ["orders:write", "warehouse:write"],
    tags: ["orders", "tier-1"],
    x: 42,
    y: 64,
  },
  {
    id: "salesforce",
    name: "Salesforce production org",
    shortName: "Salesforce",
    provider: "Salesforce",
    kind: "SaaS",
    environment: "Production",
    status: "warning",
    owner: "Revenue systems",
    description: "External CRM destination currently reporting elevated rate limiting.",
    dependencies: [],
    dependents: ["sync-worker", "support-dashboard"],
    region: "External",
    permissions: ["api:read", "api:write"],
    tags: ["saas", "crm", "external"],
    x: 50,
    y: 22,
  },
  {
    id: "customer-db",
    name: "Customer PostgreSQL",
    shortName: "Customer DB",
    provider: "AWS",
    kind: "PostgreSQL",
    environment: "Production",
    status: "healthy",
    owner: "Customer domain",
    description: "Primary customer database used by the Customer API.",
    dependencies: ["aws"],
    dependents: ["customer-api"],
    region: "us-east-1",
    permissions: ["customer:read", "customer:write"],
    tags: ["database", "customer"],
    x: 13,
    y: 84,
  },
  {
    id: "kafka",
    name: "Enterprise event bus",
    shortName: "Kafka",
    provider: "AWS",
    kind: "Event broker",
    environment: "Production",
    status: "healthy",
    owner: "Platform operations",
    description: "Multi-tenant Kafka cluster carrying order and integration events.",
    dependencies: ["eks"],
    dependents: ["order-service"],
    region: "us-east-1",
    permissions: ["topic:read", "topic:write"],
    tags: ["events", "messaging"],
    x: 45,
    y: 84,
  },
  {
    id: "snowflake",
    name: "Analytics warehouse",
    shortName: "Snowflake",
    provider: "Snowflake",
    kind: "Data warehouse",
    environment: "Production",
    status: "critical",
    owner: "Data platform",
    description: "Warehouse destination blocked by the production egress policy.",
    dependencies: [],
    dependents: ["order-service"],
    region: "External",
    permissions: ["warehouse:write"],
    tags: ["warehouse", "external", "blocked"],
    x: 66,
    y: 84,
  },
  {
    id: "support-dashboard",
    name: "Support operations dashboard",
    shortName: "Support",
    provider: "Internal",
    kind: "Web application",
    environment: "Production",
    status: "warning",
    owner: "Customer operations",
    description: "Operational view that depends on order and customer data freshness.",
    dependencies: ["order-service", "salesforce"],
    dependents: [],
    region: "Internal",
    permissions: ["support:read"],
    tags: ["support", "internal"],
    x: 86,
    y: 84,
  },
];

export const graphEdges: Array<[string, string]> = [
  ["acme", "aws"],
  ["acme", "azure"],
  ["acme", "okta"],
  ["aws", "eks"],
  ["azure", "aks"],
  ["eks", "customer-api"],
  ["eks", "order-service"],
  ["okta", "customer-api"],
  ["eks", "customer-db"],
  ["customer-db", "customer-api"],
  ["customer-api", "order-service"],
  ["eks", "kafka"],
  ["kafka", "order-service"],
  ["snowflake", "order-service"],
  ["aks", "sync-worker"],
  ["salesforce", "sync-worker"],
  ["order-service", "support-dashboard"],
  ["salesforce", "support-dashboard"],
];

export const mappingSuggestions: MappingSuggestion[] = [
  {
    id: "map-cid",
    source: "legacy_mysql",
    sourceTable: "customer_master",
    sourceField: "CID",
    sourceType: "bigint",
    targetField: "customer.id",
    targetType: "uuid",
    confidence: 98.4,
    status: "pending",
    evidence: ["integer compatibility", "uniqueness profile", "relationship similarity", "sample overlap"],
  },
  {
    id: "map-email",
    source: "legacy_mysql",
    sourceTable: "customer_master",
    sourceField: "email_address",
    sourceType: "varchar(320)",
    targetField: "customer.email",
    targetType: "text",
    confidence: 96.8,
    status: "pending",
    evidence: ["domain overlap", "format distribution", "null profile"],
  },
  {
    id: "map-name",
    source: "legacy_mysql",
    sourceTable: "customer_master",
    sourceField: "full_name",
    sourceType: "varchar(180)",
    targetField: "customer.name",
    targetType: "jsonb",
    confidence: 88.1,
    status: "pending",
    evidence: ["token shape", "sample overlap", "field-name affinity"],
  },
  {
    id: "map-status",
    source: "legacy_mysql",
    sourceTable: "customer_master",
    sourceField: "state_code",
    sourceType: "char(2)",
    targetField: "customer.status",
    targetType: "enum",
    confidence: 74.2,
    status: "pending",
    evidence: ["value overlap", "relationship cardinality", "business-rule ambiguity"],
  },
  {
    id: "map-phone",
    source: "legacy_mysql",
    sourceTable: "customer_master",
    sourceField: "phone",
    sourceType: "varchar(40)",
    targetField: "customer.phone",
    targetType: "text",
    confidence: 91.6,
    status: "pending",
    evidence: ["format distribution", "country-code overlap", "uniqueness profile"],
  },
];

export const apiEndpoints: ApiEndpoint[] = [
  {
    id: "customer-get",
    service: "Customer API",
    method: "GET",
    path: "/customer/{id}",
    protocol: "REST",
    auth: "OIDC bearer token",
    discoveryStatus: "observed",
    responseFields: [
      { name: "CID", type: "integer", nullable: false },
      { name: "email_address", type: "string", nullable: false },
      { name: "full_name", type: "string", nullable: true },
      { name: "state_code", type: "string", nullable: true },
    ],
  },
  {
    id: "customer-search",
    service: "Customer API",
    method: "POST",
    path: "/customer/search",
    protocol: "REST",
    auth: "OIDC bearer token",
    discoveryStatus: "needs-review",
    responseFields: [
      { name: "items", type: "array", nullable: false },
      { name: "next_cursor", type: "string", nullable: true },
    ],
  },
  {
    id: "customer-orders",
    service: "Customer API",
    method: "GET",
    path: "/customer/{id}/orders",
    protocol: "REST",
    auth: "OIDC bearer token",
    discoveryStatus: "observed",
    responseFields: [
      { name: "order_id", type: "string", nullable: false },
      { name: "amount", type: "number", nullable: false },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    id: "soap-customer",
    service: "Legacy Account Service",
    method: "POST",
    path: "/AccountService/FindCustomer",
    protocol: "SOAP",
    auth: "Service account",
    discoveryStatus: "needs-review",
    responseFields: [
      { name: "ClientNumber", type: "string", nullable: false },
      { name: "Email", type: "string", nullable: true },
      { name: "RegionCode", type: "string", nullable: true },
    ],
  },
  {
    id: "account-status",
    service: "Legacy Account Service",
    method: "GET",
    path: "/AccountService/Status/{clientNumber}",
    protocol: "SOAP",
    auth: "mTLS",
    discoveryStatus: "observed",
    responseFields: [
      { name: "statusCode", type: "string", nullable: false },
      { name: "updated", type: "timestamp", nullable: false },
    ],
  },
];

export const compatibilityChecks: CompatibilityCheck[] = [
  {
    id: "k8s",
    category: "Infrastructure",
    label: "Kubernetes 1.31 is supported",
    status: "pass",
    blocking: false,
    detail: "Both EKS and AKS report a supported control plane version.",
    remediation: "No action required.",
  },
  {
    id: "capacity",
    category: "Infrastructure",
    label: "CPU and memory capacity available",
    status: "pass",
    blocking: false,
    detail: "The target namespace has schedulable capacity for the release profile.",
    remediation: "No action required.",
  },
  {
    id: "gpu",
    category: "Infrastructure",
    label: "GPU runtime unavailable",
    status: "warning",
    blocking: false,
    detail: "The AI workload is configured for optional acceleration and can use CPU fallback.",
    remediation: "Use the cpu-medium profile or attach an approved GPU node pool.",
  },
  {
    id: "snowflake-network",
    category: "Network",
    label: "Snowflake endpoint blocked by egress policy",
    status: "blocked",
    blocking: true,
    detail: "The production egress gateway has no route to the warehouse endpoint.",
    remediation: "Add the approved Snowflake host to the production egress policy.",
  },
  {
    id: "internal-api",
    category: "Network",
    label: "Internal customer API is reachable",
    status: "pass",
    blocking: false,
    detail: "Preflight completed a TLS request from the target namespace.",
    remediation: "No action required.",
  },
  {
    id: "oauth",
    category: "Security",
    label: "Workload OAuth configuration verified",
    status: "pass",
    blocking: false,
    detail: "Token audience, issuer, and signing key match the target workload.",
    remediation: "No action required.",
  },
  {
    id: "iam",
    category: "Security",
    label: "Warehouse write permission is missing",
    status: "blocked",
    blocking: true,
    detail: "The deployment role cannot write to the target Snowflake schema.",
    remediation: "Bind the reviewed warehouse-write policy to the workload role.",
  },
  {
    id: "schema",
    category: "Data",
    label: "Core customer schema is compatible",
    status: "pass",
    blocking: false,
    detail: "Required canonical fields have compatible source fields.",
    remediation: "No action required.",
  },
  {
    id: "nullable",
    category: "Data",
    label: "Three nullable customer fields",
    status: "warning",
    blocking: false,
    detail: "The adapter can represent missing source values without dropping records.",
    remediation: "Confirm the customer profile rules for incomplete records.",
  },
  {
    id: "timestamp",
    category: "Data",
    label: "Timestamp encoding is incompatible",
    status: "blocked",
    blocking: true,
    detail: "The legacy service emits local timestamps without an explicit offset.",
    remediation: "Configure the source timezone and require UTC output before promotion.",
  },
  {
    id: "kafka-lag",
    category: "Network",
    label: "Kafka consumer lag is near the review threshold",
    status: "warning",
    blocking: false,
    detail: "The order consumer is within the simulation review window before its next canary.",
    remediation: "Confirm consumer capacity and topic retention before promotion.",
  },
  {
    id: "token-rotation",
    category: "Security",
    label: "Workload token rotation is due during the canary",
    status: "warning",
    blocking: false,
    detail: "The mock identity provider will rotate its signing key while traffic is being observed.",
    remediation: "Verify the next signing key is published before the release window.",
  },
  {
    id: "soap-tls",
    category: "Security",
    label: "Legacy SOAP service uses an older TLS policy",
    status: "warning",
    blocking: false,
    detail: "The compatibility scan accepts the service for a read-only canary with an exception record.",
    remediation: "Record the mTLS exception and schedule a service contract modernization task.",
  },
];

export const deploymentRecord: DeploymentRecord = {
  id: "DX-842",
  version: "customer-graph-1.8.0",
  environment: "Production",
  status: "healthy",
  startedAt: "Simulation snapshot, 09:18",
  requests: "1,824,921",
  successRate: "99.94%",
  p95Latency: "241 ms",
  errorRate: "0.06%",
  cost: "$31.42",
};

export const activeIncident: IncidentRecord = {
  id: "DX-1842",
  title: "Salesforce customer sync degradation",
  severity: "High",
  state: "Investigating",
  customer: "ACME",
  startedAt: "14:32",
  detectedAt: "14:33",
  probableCause: "Salesforce API rate limit exceeded",
  confidence: 93,
  affectedServices: ["Salesforce sync worker", "Customer context enrichment", "Support dashboard"],
  affectedWorkflows: ["Salesforce customer sync", "AI customer context"],
  evidence: [
    { id: "e1", label: "Salesforce 429 responses", value: "+812%", signal: "degradation" },
    { id: "e2", label: "Salesforce request volume", value: "+317%", signal: "change" },
    { id: "e3", label: "Related release", value: "11 minutes before onset", signal: "correlation" },
    { id: "e4", label: "Observed scope", value: "3 services, 2 workflows", signal: "scope" },
  ],
  remediation: [
    "Enable the customer projection cache with a five-minute TTL",
    "Reduce connector concurrency to eight workers",
    "Move failed sync events to the retry queue",
    "Keep automatic production approval disabled during containment",
  ],
};

export const labServices: LabService[] = [
  { id: "postgres", name: "Customer database", technology: "PostgreSQL 16", status: "healthy", latency: "8 ms", message: "Schema and credentials verified", availableFaults: ["wrong-credentials", "schema-drift"] },
  { id: "mysql", name: "Legacy customer master", technology: "MySQL 8", status: "healthy", latency: "14 ms", message: "Sample discovery enabled", availableFaults: ["schema-drift", "corrupt-records"] },
  { id: "redis", name: "Customer cache", technology: "Redis 7", status: "healthy", latency: "2 ms", message: "Projection cache available", availableFaults: ["network-partition"] },
  { id: "kafka", name: "Enterprise event bus", technology: "Kafka", status: "healthy", latency: "11 ms", message: "Topics responding", availableFaults: ["network-partition", "rate-limit"] },
  { id: "customer-api", name: "Customer API", technology: "FastAPI", status: "healthy", latency: "182 ms", message: "Smoke tests passing", availableFaults: ["slow-api", "network-partition"] },
  { id: "soap-api", name: "Legacy account service", technology: "SOAP", status: "warning", latency: "612 ms", message: "TLS policy needs review", availableFaults: ["slow-api", "network-partition"] },
  { id: "salesforce", name: "Salesforce connector", technology: "Mock REST API", status: "healthy", latency: "244 ms", message: "API quota available", availableFaults: ["rate-limit", "network-partition"] },
  { id: "okta", name: "Workload identity", technology: "Mock OIDC", status: "healthy", latency: "31 ms", message: "Signing key valid", availableFaults: ["expired-token"] },
  { id: "legacy-worker", name: "Legacy order worker", technology: "Python", status: "healthy", latency: "96 ms", message: "Consumer group active", availableFaults: ["wrong-credentials", "rate-limit"] },
  { id: "ai-service", name: "Customer context service", technology: "FastAPI", status: "healthy", latency: "321 ms", message: "Fallback profile active", availableFaults: ["slow-api", "corrupt-records"] },
];

export const playbookYaml = `customer: acme

salesforce:
  max_concurrency: 8
  retry_policy: exponential
  cache_ttl: 300

security:
  require_mfa: true
  production_approval: required

deployment:
  strategy: canary
  max_error_rate: 0.5%
`;

export const memoryPatterns: MemoryPattern[] = [
  {
    id: "salesforce-enterprise",
    title: "Salesforce Enterprise Pattern",
    provider: "Salesforce",
    confidence: "High",
    deployments: 5,
    knownFailures: 6,
    lastValidated: "After DX-842",
    summary: "Five recorded deployments converged on a small set of authentication, rate-limit, and schema controls.",
    requirements: ["OIDC client credentials", "Schema-level write policy", "Customer identifier projection", "Explicit UTC timestamps"],
    tests: ["Token audience", "Write policy dry run", "Timestamp offset validation", "429 backoff behavior"],
    strategy: "Canary at 1%, 5%, 25%, and 50% with rollback at 0.5% errors",
  },
  {
    id: "legacy-oracle-customer",
    title: "Legacy Oracle Customer Pattern",
    provider: "Oracle",
    confidence: "Medium",
    deployments: 2,
    knownFailures: 3,
    lastValidated: "After DX-731",
    summary: "Legacy customer identifiers require explicit source-system ownership and null-preserving transformations.",
    requirements: ["Source timezone declaration", "Nullable field policy", "Source-system identifier namespace"],
    tests: ["Null profile comparison", "Timezone offset comparison", "Identifier collision check"],
    strategy: "Shadow read validation before any production write",
  },
  {
    id: "soap-modernization",
    title: "SOAP Modernization Pattern",
    provider: "Internal",
    confidence: "High",
    deployments: 3,
    knownFailures: 4,
    lastValidated: "After DX-808",
    summary: "Legacy SOAP services can be isolated behind a versioned adapter when contract drift is captured first.",
    requirements: ["WSDL snapshot", "Service account rotation procedure", "MTLS exception record"],
    tests: ["WSDL contract comparison", "Certificate chain validation", "Partial response handling"],
    strategy: "Canary reads followed by a separately approved write path",
  },
];
